name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Installing libusb (linux)
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: sudo apt-get install libusb-1.0-0-dev
    - run: mkdir build
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.4.0
      with:
        version: 5.12.7
    - name: Configure
      working-directory: build
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install ..
    - name: Build
      working-directory: build
      shell: bash
      run: cmake --build . --config Release







